version: "3.1"

services:
  adonisboilerplate_db:
    image: postgres
    container_name: adonisboilerplate
    environment:
      POSTGRES_USER: adonisboilerplate
      POSTGRES_PASSWORD: adonisboilerplate
      POSTGRES_DB: adonisboilerplate
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: 512M
