version: "3.1"

services:
  plutus_db:
    image: postgres
    container_name: plutus
    environment:
      POSTGRES_USER: plutus
      POSTGRES_PASSWORD: plutus
      POSTGRES_DB: plutus
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: 512M
